// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsABzxSRJdvV3X54BHbU5DO1TSr0P0r6k',
    appId: '1:940408505005:web:2792929a9ed4d28c5b7c24',
    messagingSenderId: '940408505005',
    projectId: 'erpapay-6aae3',
    authDomain: 'erpapay-6aae3.firebaseapp.com',
    storageBucket: 'erpapay-6aae3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBySZgyCXCwrDCzCeXDet_sOh8sNXcFLDQ',
    appId: '1:940408505005:android:2fce26a28c9a3ea75b7c24',
    messagingSenderId: '940408505005',
    projectId: 'erpapay-6aae3',
    storageBucket: 'erpapay-6aae3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQQm4WO-tDtXlIZJd5GGNqtZi_9DZWXOM',
    appId: '1:940408505005:ios:d4136cfded01c3a65b7c24',
    messagingSenderId: '940408505005',
    projectId: 'erpapay-6aae3',
    storageBucket: 'erpapay-6aae3.appspot.com',
    iosClientId: '940408505005-d0g1v06j4phsi3rud87e9oe8d1vu1th4.apps.googleusercontent.com',
    iosBundleId: 'com.example.erpapay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQQm4WO-tDtXlIZJd5GGNqtZi_9DZWXOM',
    appId: '1:940408505005:ios:b649cca309fb5d455b7c24',
    messagingSenderId: '940408505005',
    projectId: 'erpapay-6aae3',
    storageBucket: 'erpapay-6aae3.appspot.com',
    iosClientId: '940408505005-mg704paele5f22nd5lbiui9d0ojkieu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.erpapay.RunnerTests',
  );
}
